on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{secrets.GITHUB_TOKEN}}
          package-name: bibi-gpt
